### ISSUE TITLE
[modsecurity-crs-nginx] ERROLOG does not reflect REAL_IP_HEADER

### ISSUE THREAD

**Issue by mhupfauer** [coreruleset/modsecurity-docker#129]
The nginx container does not properly reflect the `REAL_IP_HEADER` in the `ERRORLOG` file within property `client_ip`.

docker-compose.yml
```yml
environment:
   SET_REAL_IP_FROM: "0.0.0.0/0"
   REAL_IP_HEADER: "X-Forwarded-For"
   REAL_IP_RECURSIVE: "on"
```

waf.log (ERRORLOG)
```yml
[...] clientip: 192.168.44.2 
```
This is the internal IP of the public facing traefik container for SSL termination. The `docker compose logs` output formats the client ip properly in front of the error message.

With `modsecurity-crs-apache` and the following docker-compose it is working properly though.

docker-compose.yml
```yml
environment:
   REMOTEIP_INT_PROXY: "192.0.0.0/8"
```
