### ISSUE TITLE
SSL certificated are not loaded in Nginx image

### ISSUE THREAD

**Issue by andrei-piarainc** [coreruleset/modsecurity-docker#149]
We were using tag `owasp/modsecurity-crs:3.3.2-nginx` to build our application image on top of it. It worked fine until image under that tag was updated in DockerHub and our SSL certificates suddenly stopped working. No changes were done on our side, we just rebuilt our image with the same source code and the same FROM tag. If we build from original image of the same underlying Nginx version - it works ok.

The issue is reproducible with current `owasp/modsecurity-crs:3.3.2-nginx` and also with latest `owasp/modsecurity-crs:3.3.4-nginx-202209221209`

There is no issue with image `owasp/modsecurity-crs@sha256:4ab21fb9a6cab32fc04b15017b4dce68c6080ca6293726321f31077a7cf76468` which was under the `owasp/modsecurity-crs:3.3.2-nginx` tag at the time of our successful build 19.11.2021.

We attach SSL certificate from disk using `ssl_certificate` and `ssl_certificate_key` settings in `server` section of Nginx config. Actually those cert files are mapped to container as `secrets` in `docker-compose.yml` file.

Issue manifests itself as an SSL error when trying to open application page in Chrome browser, and missing SSL certificate, substituted  somehow with self-signed one. See screenshots below:

1.
![image](https://user-images.githubusercontent.com/87129660/192013309-5c77b737-0e3b-4275-a47d-1779c3423f0c.png)

2.
![image](https://user-images.githubusercontent.com/87129660/192013342-87598b13-6f8f-4a49-8eab-bc035c92440b.png)

**Comment by theseion** [comment]
Hi @andrei-piarainc. This is a duplicate of https://github.com/coreruleset/modsecurity-crs-docker/issues/90, correct? I will close this one. Let me know if there's a reason to keep both.

**Comment by andrei-piarainc** [comment]
> Hi @andrei-piarainc. This is a duplicate of [coreruleset/modsecurity-crs-docker#90](https://github.com/coreruleset/modsecurity-crs-docker/issues/90), correct? I will close this one. Let me know if there's a reason to keep both.

Right. Just created #90 and somehow was not able to find it after that via search;)

**Comment by TafkaMax** [comment]
How do you pass the keys? Im getting 

```
2022/10/13 13:02:20 [emerg] 1#1: SSL_CTX_use_PrivateKey("/etc/nginx/conf/server.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx: [emerg] SSL_CTX_use_PrivateKey("/etc/nginx/conf/server.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
```
```
  nginx-modsecurity-proxy:
    container_name: nginx-modsecurity-proxy
    hostname: nginx-modsecurity-proxy
    image: owasp/modsecurity-crs:nginx
    restart: unless-stopped
    volumes:
        - /opt/weblate/nginx_modsecurity/server.crt:/etc/nginx/conf/server.crt:ro
        - /opt/weblate/nginx_modsecurity/server.key:/etc/conf/conf/server.key:ro
        - /opt/weblate/nginx_modsecurity/log:/var/log/nginx/access.log
        - /opt/weblate/nginx_modsecurity/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
    ports:
        - "80:80"
        - "443:443"
    env_file:
      - '/opt/weblate/nginx_modsecurity/env-nginx_modsecurity'

```
